#!/usr/bin/env python3

r'''Utilities installer
'''

from argparse import RawTextHelpFormatter, ArgumentParser
import os, sys
from posix import listdir
from os.path import dirname, basename, splitext, join, exists, abspath
from site import getsitepackages
from importlib import import_module
from mkdo import mkdo
from subprocess import run

this_name = splitext(basename(__file__))[0]
this_dir = abspath(dirname(__file__))

verbose = False

def vprint(*args, **kwargs):
    if verbose:
        print(*args, file=sys.stderr, **kwargs)

class NoException(Exception):
    pass

required = ['filelock']

def install():
    bin = '/usr/local/bin'
    bin = input(f'target bin directory: {bin}? ') or bin

    pth = join(getsitepackages()[0], 'util.pth')
    pth = input(f'target pth file: {pth}? ') or pth

    for m in required:
        cmd = f'pip3 install {m}'
        print (cmd)
        run(cmd, shell=True)

    try:
        with open(pth, 'w') as f:
            vprint(f'{pth}: {this_dir}')
            print(this_dir, file=f)

        for fname in sorted(listdir(this_dir)):
            cmd, ext = splitext(fname)
            if ext=='.py':
                if '# install-me' in open(join(this_dir, fname)).read():
                    vprint(f'mkdo {cmd}')
                    mkdo(cmd, bin)
                    m = import_module(cmd)
                    desc = m.__doc__.split('\n')[0]
                    print(f'{cmd} - {desc}')

    except PermissionError:
        print('Permission error: try using `sudo ./install`.')

def main():
    global verbose

    parser = ArgumentParser(prog=this_name,
        formatter_class=RawTextHelpFormatter, description=__doc__)

    parser.add_argument('-v', action='store_true', help='show debugging output')
    parser.add_argument('-e', action='store_true', help='raise exception on error')

    args = parser.parse_args()
    verbose = args.v
    etype = NoException if args.e else Exception # conditional exception handling

    try:
        install()
    except etype as e: # Best if replaced with explicit exception
        print (e, file=sys.stderr)
        exit(1)


main()

